In [2]:
#imports
import pandas as pd
import numpy as pd
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import validation_curve
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt
import seaborn as sns
import keras

In [36]:
#read data
df = pd.read_csv('/content/sample_data/pub2-dataset.csv')
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 991,Unnamed: 992,Unnamed: 993,Unnamed: 994,Unnamed: 995,Unnamed: 996,Unnamed: 997,Unnamed: 998,Unnamed: 999,L
0,-2.030000e-06,0.000020,0.000037,0.000032,0.000041,0.000054,0.000070,0.000082,0.000088,0.000088,...,0.000049,0.000034,0.000022,0.000020,0.000031,0.000046,0.000061,0.000076,0.000088,1.0
1,-1.760000e-06,0.000015,0.000029,0.000028,0.000053,0.000084,0.000114,0.000136,0.000153,0.000169,...,0.000077,0.000070,0.000065,0.000058,0.000050,0.000039,0.000032,0.000025,0.000025,1.0
2,-1.390000e-06,0.000019,0.000029,0.000050,0.000084,0.000111,0.000135,0.000150,0.000160,0.000157,...,0.000113,0.000100,0.000084,0.000069,0.000052,0.000033,0.000021,0.000012,0.000012,1.0
3,-3.600000e-06,0.000049,0.000070,0.000067,0.000121,0.000150,0.000149,0.000141,0.000107,0.000075,...,0.000102,0.000154,0.000191,0.000204,0.000192,0.000172,0.000156,0.000137,0.000119,1.0
4,-3.150000e-07,0.000014,0.000044,0.000126,0.000209,0.000259,0.000266,0.000230,0.000166,0.000108,...,0.000069,0.000054,0.000135,0.000181,0.000207,0.000210,0.000198,0.000175,0.000158,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,-1.150000e-06,0.000021,0.000072,0.000187,0.000322,0.000413,0.000451,0.000464,0.000464,0.000451,...,0.000374,0.000394,0.000381,0.000336,0.000269,0.000215,0.000204,0.000211,0.000197,1.0
116,-2.060000e-07,0.000008,0.000097,0.000288,0.000472,0.000560,0.000542,0.000464,0.000382,0.000308,...,0.000625,0.000573,0.000503,0.000422,0.000338,0.000280,0.000269,0.000288,0.000306,1.0
117,-4.140000e-07,0.000014,0.000141,0.000407,0.000633,0.000702,0.000607,0.000408,0.000184,0.000083,...,0.000157,0.000142,0.000131,0.000146,0.000146,0.000157,0.000190,0.000186,0.000138,1.0
118,-1.650000e-07,0.000018,0.000203,0.000514,0.000633,0.000508,0.000303,0.000119,0.000067,0.000082,...,0.000074,0.000040,0.000100,0.000110,0.000077,0.000054,0.000044,0.000031,0.000048,1.0
119,-1.280000e-06,0.000033,0.000271,0.000490,0.000467,0.000262,0.000102,0.000064,0.000078,0.000053,...,0.000160,0.000181,0.000147,0.000128,0.000140,0.000177,0.000191,0.000170,0.000093,1.0

In [37]:
#shuffle data
df = df.sample(frac=1).reset_index()

df

,index,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 991,Unnamed: 992,Unnamed: 993,Unnamed: 994,Unnamed: 995,Unnamed: 996,Unnamed: 997,Unnamed: 998,Unnamed: 999,L
0,16,-1.060000e-06,0.000011,0.000016,0.000016,0.000025,0.000033,0.000044,0.000053,0.000059,...,0.000013,0.000018,0.000020,0.000020,0.000021,0.000023,0.000024,0.000024,0.000024,0.0
1,112,-1.420000e-05,0.000132,0.000187,0.000142,0.000228,0.000269,0.000301,0.000312,0.000333,...,0.000165,0.000156,0.000165,0.000181,0.000200,0.000214,0.000224,0.000229,0.000226,1.0
2,92,-6.740000e-07,0.000006,0.000051,0.000145,0.000265,0.000351,0.000378,0.000353,0.000290,...,0.000155,0.000164,0.000128,0.000065,0.000037,0.000084,0.000139,0.000175,0.000199,1.0
3,37,-6.180000e-07,0.000013,0.000141,0.000401,0.000611,0.000660,0.000546,0.000354,0.000218,...,0.000045,0.000018,0.000043,0.000109,0.000138,0.000140,0.000107,0.000077,0.000096,1.0
4,66,-2.760000e-07,0.000003,0.000005,0.000007,0.000015,0.000034,0.000057,0.000066,0.000077,...,0.000134,0.000146,0.000153,0.000158,0.000161,0.000162,0.000152,0.000129,0.000098,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,77,-3.950000e-07,0.000006,0.000026,0.000070,0.000123,0.000159,0.000167,0.000164,0.000151,...,0.000059,0.000113,0.000142,0.000132,0.000087,0.000039,0.000024,0.000052,0.000106,0.0
116,6,-7.850000e-07,0.000013,0.000107,0.000292,0.000400,0.000348,0.000222,0.000100,0.000073,...,0.000259,0.000298,0.000323,0.000293,0.000168,0.000057,0.000041,0.000028,0.000044,1.0
117,53,-2.760000e-07,0.000003,0.000012,0.000035,0.000055,0.000047,0.000036,0.000048,0.000071,...,0.000038,0.000104,0.000153,0.000188,0.000196,0.000197,0.000173,0.000129,0.000086,0.0
118,36,-1.050000e-06,0.000016,0.000101,0.000276,0.000446,0.000513,0.000499,0.000437,0.000339,...,0.000066,0.000050,0.000025,0.000057,0.000114,0.000138,0.000126,0.000094,0.000086,1.0
119,17,-2.340000e-07,0.000002,0.000008,0.000019,0.000035,0.000048,0.000061,0.000075,0.000088,...,0.000038,0.000046,0.000056,0.000065,0.000070,0.000071,0.000066,0.000056,0.000048,0.0

In [38]:
df = df.drop('index', axis=1)
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 991,Unnamed: 992,Unnamed: 993,Unnamed: 994,Unnamed: 995,Unnamed: 996,Unnamed: 997,Unnamed: 998,Unnamed: 999,L
0,-1.060000e-06,0.000011,0.000016,0.000016,0.000025,0.000033,0.000044,0.000053,0.000059,0.000062,...,0.000013,0.000018,0.000020,0.000020,0.000021,0.000023,0.000024,0.000024,0.000024,0.0
1,-1.420000e-05,0.000132,0.000187,0.000142,0.000228,0.000269,0.000301,0.000312,0.000333,0.000357,...,0.000165,0.000156,0.000165,0.000181,0.000200,0.000214,0.000224,0.000229,0.000226,1.0
2,-6.740000e-07,0.000006,0.000051,0.000145,0.000265,0.000351,0.000378,0.000353,0.000290,0.000199,...,0.000155,0.000164,0.000128,0.000065,0.000037,0.000084,0.000139,0.000175,0.000199,1.0
3,-6.180000e-07,0.000013,0.000141,0.000401,0.000611,0.000660,0.000546,0.000354,0.000218,0.000221,...,0.000045,0.000018,0.000043,0.000109,0.000138,0.000140,0.000107,0.000077,0.000096,1.0
4,-2.760000e-07,0.000003,0.000005,0.000007,0.000015,0.000034,0.000057,0.000066,0.000077,0.000093,...,0.000134,0.000146,0.000153,0.000158,0.000161,0.000162,0.000152,0.000129,0.000098,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,-3.950000e-07,0.000006,0.000026,0.000070,0.000123,0.000159,0.000167,0.000164,0.000151,0.000135,...,0.000059,0.000113,0.000142,0.000132,0.000087,0.000039,0.000024,0.000052,0.000106,0.0
116,-7.850000e-07,0.000013,0.000107,0.000292,0.000400,0.000348,0.000222,0.000100,0.000073,0.000122,...,0.000259,0.000298,0.000323,0.000293,0.000168,0.000057,0.000041,0.000028,0.000044,1.0
117,-2.760000e-07,0.000003,0.000012,0.000035,0.000055,0.000047,0.000036,0.000048,0.000071,0.000087,...,0.000038,0.000104,0.000153,0.000188,0.000196,0.000197,0.000173,0.000129,0.000086,0.0
118,-1.050000e-06,0.000016,0.000101,0.000276,0.000446,0.000513,0.000499,0.000437,0.000339,0.000209,...,0.000066,0.000050,0.000025,0.000057,0.000114,0.000138,0.000126,0.000094,0.000086,1.0
119,-2.340000e-07,0.000002,0.000008,0.000019,0.000035,0.000048,0.000061,0.000075,0.000088,0.000100,...,0.000038,0.000046,0.000056,0.000065,0.000070,0.000071,0.000066,0.000056,0.000048,0.0

In [39]:
from sklearn. model_selection import train_test_split
y = df.pop('L')
x = df

In [40]:
x = x.values.reshape(x.shape[0], x.shape[1], 1)
print(x.shape)

(120, 1000, 1)

In [41]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [42]:
from keras.models import Sequential
from keras.layers import Dense, Conv1D, Flatten, MaxPooling1D
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [43]:
#cnn-1d model
model = Sequential()
model.add(Conv1D(64, 2, activation="relu", input_shape=(1000,1)))
model.add(Dense(16, activation="relu"))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(2, activation = 'softmax'))
model.compile(loss = 'sparse_categorical_crossentropy', 
     optimizer = "adam",               
              metrics = ['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv1d_1 (Conv1D)           (None, 999, 64)           192

 dense_2 (Dense)             (None, 999, 16)           1040

 max_pooling1d_1 (MaxPooling  (None, 499, 16)          0
 1D)

 flatten_1 (Flatten)         (None, 7984)              0

 dense_3 (Dense)             (None, 2)                 15970

=================================================================
Total params: 17,202
Trainable params: 17,202
Non-trainable params: 0
_________________________________________________________________

In [48]:
#fit model
model.fit(x_train, y_train, batch_size=2,epochs=100, verbose=0)

acc = model.evaluate(x_train, y_train)
print("Loss:", acc[0], " Accuracy:", acc[1])

3/3 [==============================] - 0s 16ms/step - loss: 0.5276 - accuracy: 0.6979
Loss: 0.5275935530662537  Accuracy: 0.6979166865348816

In [54]:
#metrics
pred = model.predict(x_test)
y_pred = pred.argmax(axis=-1)
cm = confusion_matrix(y_test, y_pred)
print(cm)
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import validation_curve
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
print("f1 score macro",metrics.f1_score(y_test , y_pred, average='macro')) 
print("precision score",metrics.precision_score(y_test, y_pred, average='macro'))
print("recall score",metrics.recall_score(y_test, y_pred, average='macro')) 
print("accuracy", metrics.accuracy_score(y_test, y_pred), "\n")

[[ 5  6]
 [ 2 11]]
f1 score macro 0.6444444444444445
precision score 0.680672268907563
recall score 0.6503496503496503
accuracy 0.6666666666666666